version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: on-failure

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: on-failure

  logstash:
    container_name: logstash
    image: logstash:7.16.2
    volumes:
      - ./logstash/conf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./driver/postgresql-42.3.1.jar:/usr/share/logstash/postgresql-42.3.1.jar
    depends_on:
      - elasticsearch
      - postgres
    ports:
      - "5044:5044"
    restart: on-failure

  kibana:
    container_name: kibana
    image: kibana:7.16.2
    environment:
      - ELASTICSEARCH_URL=elasticsearch:9200
    depends_on:
      - elasticsearch
      - logstash
    ports:
      - "5601:5601"
    restart: on-failure